defaults:
  - env/realworld_ur5_reach@env.train
  - env/realworld_ur5_reach@env.eval
  - model/pi0_5@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 2
  component_placement:
    actor:
      node_group: "gpu"
      placement: 0
    env:
      node_group: ur5
      placement: 0
    rollout:
      node_group: "gpu"
      placement: 0
  node_groups:
    - label: "gpu"
      node_ranks: 0
    - label: ur5
      node_ranks: 1
      hardware:
        type: UR5
        configs:
          - robot_ip: ROBOT_IP
            camera_serials: ["CAMERA_SERIAL1", "CAMERA_SERIAL2", "CAMERA_SERIAL3"]
            node_rank: 1

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "realworld_ur5_openpi_pi05_eval"
    logger_backends: ["tensorboard"]

  max_epochs: 1
  max_steps: -1
  only_eval: True
  val_check_interval: 1
  save_interval: -1

  resume_dir: null
  ckpt_path: null

algorithm:
  normalize_advantages: True
  kl_penalty: kl
  group_size: 1
  reward_coef: 1.0

  rollout_epoch: 1
  eval_rollout_epoch: 1
  reward_type: chunk_level
  logprob_type: chunk_level
  entropy_type: chunk_level
  update_epoch: 1

  adv_type: gae
  loss_type: actor_critic
  loss_agg_func: "token-mean"
  bootstrap_type: always
  kl_beta: 0.0
  entropy_bonus: 0.0
  clip_ratio_high: 0.2
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 0.2
  huber_delta: 10.0

  gamma: 0.99
  gae_lambda: 0.95

  filter_rewards: False
  rewards_lower_bound: 0.0
  rewards_upper_bound: 1.0

  sampling_params:
    do_sample: True
    temperature_train: 1.0
    temperature_eval: 0.6
    top_k: 50
    top_p: 1.0
    repetition_penalty: 1.0
    add_BOS: False

  length_params:
    max_new_token: null
    max_length: 1024
    min_length: 1

env:
  group_name: "EnvGroup"
  no_gripper: False
  use_spacemouse: False
  main_image_key: wrist_1

  train:
    total_num_envs: 1
    auto_reset: True
    ignore_terminations: False
    max_episode_steps: 100
    max_steps_per_rollout_epoch: 100
    group_size: 1
    override_cfg:
      is_dummy: False
      controller_backend: "custom"
      controller_cls_path: "rlinf.envs.realworld.ur5.ur_rtde_controller:CustomUR5Controller"
      robot_ip: ROBOT_IP
      camera_serials: ["CAMERA_SERIAL1", "CAMERA_SERIAL2", "CAMERA_SERIAL3"]
      gripper_type: "robotiq"
      gripper_port: 63352
      tcp_offset: null
      move_acc: 0.25
      move_vel: 0.25
      target_ee_pose: TARGET_EE_POSE
  eval:
    total_num_envs: 1
    auto_reset: True
    ignore_terminations: False
    max_episode_steps: 100
    max_steps_per_rollout_epoch: 100
    group_size: 1
    is_eval: True
    video_cfg:
      save_video: True
      video_base_dir: ${runner.logger.log_path}/video/eval
    override_cfg:
      is_dummy: False
      controller_backend: "custom"
      controller_cls_path: "rlinf.envs.realworld.ur5.ur_rtde_controller:CustomUR5Controller"
      robot_ip: ROBOT_IP
      camera_serials: ["CAMERA_SERIAL1", "CAMERA_SERIAL2", "CAMERA_SERIAL3"]
      gripper_type: "robotiq"
      gripper_port: 63352
      tcp_offset: null
      move_acc: 0.25
      move_vel: 0.25
      target_ee_pose: TARGET_EE_POSE

rollout:
  group_name: "RolloutGroup"
  generation_backend: "huggingface"
  recompute_logprobs: False
  enable_offload: False
  pipeline_stage_num: 1

  model:
    model_path: ${oc.env:REPO_PATH}/models/pi05_base_rlinf
    precision: ${actor.model.precision}

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  micro_batch_size: 1
  global_batch_size: 1
  seed: 0
  enable_offload: False

  model:
    model_path: ${oc.env:REPO_PATH}/models/pi05_base_rlinf
    model_type: "openpi"
    action_dim: 7
    num_action_chunks: 10
    add_value_head: True
    num_steps: 5
    openpi:
      config_name: "pi05_ur5_realworld"
      num_images_in_input: 3
      value_after_vlm: True
      noise_method: "flow_noise"
      action_horizon: 10
      noise_params: [0.16, 0.12, 200]
      joint_logprob: True

  optim:
    lr: 5.0e-6
    value_lr: 1.0e-4
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    clip_grad: 1.0
    critic_warmup_steps: 0

  fsdp_config:
    strategy: "fsdp"
    sharding_strategy: "no_shard"
    gradient_checkpointing: False
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

reward:
  use_reward_model: False

critic:
  use_critic_model: False
