defaults:
  - model/pi0_5@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    actor: all

runner:
  task_type: sft
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "libero_sft_openpi_pi05_train20_local"
    logger_backends: ["tensorboard"]

  max_epochs: 5000
  max_steps: -1
  val_check_interval: -1
  save_interval: 500
  resume_dir: null

data:
  train_data_paths: "/mimer/NOBACKUP/groups/naiss2024-5-164/Hanzhi/RLinf/datasets/lerobot_libero_spatial_image_train20"

algorithm:
  adv_type: gae

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  micro_batch_size: 16
  global_batch_size: 128
  seed: 0

  model:
    precision: null
    model_path: "/mimer/NOBACKUP/groups/naiss2024-5-164/Hanzhi/RLinf/models/pi05_base_rlinf"
    num_action_chunks: 10
    add_value_head: False
    is_lora: False
    lora_rank: 16
    openpi:
      config_name: "pi05_libero"
      detach_critic_input: null

  optim:
    lr: 1.0e-5
    value_lr: 1.0e-4
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-8
    weight_decay: 0.0
    clip_grad: 1.0
    warmup_style: "cosine"
    lr_warmup_steps: 100
    total_training_steps: 5000

  fsdp_config:
    strategy: "fsdp"
    sharding_strategy: "full_shard"
    use_orig_params: False
    gradient_checkpointing: False
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

reward:
  use_reward_model: False

critic:
  use_critic_model: False
